// Translation data - English and German only
const translations = {
    en: {
        // Header
        "name": "Mohammadali Forouzesh",
        "title": "DevOps Engineer | Kubernetes Administrator | Site Reliability Engineer",
        "pr-status": "Germany PR holder",
        "download-cv": "Download CV",
        "pdf-version": "PDF Version",
        "yaml-version": "YAML Version",
        "contact-me": "Contact Me",
        "email-label": "Email:",
        "phone-label": "Phone:",
        "click-to-reveal": "click to reveal!",
        "last-updated": "Last updated: November 2025",

        // Sections
        "about-me": "About Me",
        "about-text": "🚀 Results-driven DevOps Engineer with a Master's in Computer Science and 8+ years of experience in cloud architecture ☁️, Azure, AWS, CI/CD and Kubernetes. 💪 Proven ability to lead production releases and automate infrastructure. 🛠️ Expertise in end-to-end pipeline creation, containerization 🐳, and proactive monitoring 📊 to drive successful project outcomes.",

        "certifications": "Certifications",
        "cert-devops-azure": "Microsoft Certified DevOps Engineer Expert (AZ-400)",
        "cert-architect-azure": "Microsoft Certified Azure Solutions Architect Expert (AZ-305)",
        "cert-admin-azure": "Microsoft Certified Azure Administrator Associate (AZ-104)",
        "cert-fundamentals-azure": "Microsoft Certified Azure Fundamentals (AZ-900)",
        "cert-devsecops-hcl": "HCL Technologies Certified DevSecOps and SRE Associate",
        "cert-prompt-hcl": "HCL Technologies Certified Gen AI Prompt Engineering",
        "cert-genai-hcl": "HCL Technologies Certified AI & Gen AI Fundamentals",
        "cert-graphql-ndc": "NDC conferences workshop GraphQL API - Porto 2022",

        "experience": "Professional Experience",
        "position-senior-devops": "Senior DevOps Engineer",
        "company-euroclear": "Euroclear",
        "location-brussels": "Brussels, Belgium",
        "remote-germany": "(Remote from Germany)",
        "duration-2023-present": "2023 - Present",
        "exp-euroclear-1": "Designed and managed 10+ CI/CD pipelines in Azure DevOps for diverse application teams",
        "exp-euroclear-2": "Developed and maintained 5+ Infrastructure as Code (IaC) repositories using Terraform",
        "exp-euroclear-3": "Authored 20+ PowerShell scripts to automate operational tasks and deployments",
        "exp-euroclear-4": "Implemented automated monitoring, alerting, and log analysis for proactive system management",
        "exp-euroclear-5": "Led and participated in 15+ production release and launch cycles",

        "position-lead-devops": "Project Lead & Senior DevOps Consultant",
        "company-hcl": "HCL Technologies",
        "location-frankfurt": "Frankfurt, Germany",
        "exp-hcl-1": "Consulted as a Senior DevOps expert for client Euroclear, driving key project deliveries",
        "exp-hcl-2": "Delivered infrastructure automation, CI/CD, and monitoring solutions",

        "position-senior-software": "Senior Software/DevOps Engineer",
        "company-matelso": "matelso GmbH",
        "location-kaiserslautern": "Kaiserslautern, Germany",
        "on-site": "(On site)",
        "duration-2021-2023": "2021 - 2023",
        "exp-matelso-1": "Architected and maintained core backend GraphQL APIs for a SaaS platform",
        "exp-matelso-2": "Developed and enhanced 10+ microservices using .NET",
        "exp-matelso-3": "Engineered and maintained 10+ CI/CD pipelines for automated testing and deployment",
        "exp-matelso-4": "Containerized and deployed 10+ services on a Kubernetes cluster",

        "position-research": "Software Engineer & Research Assistant",
        "company-mpi": "Max Planck Institute",
        "duration-2018-2020": "2018 - 2020",
        "exp-mpi-1": "Developed interactive data visualization dashboards using Python and web technologies",
        "exp-mpi-2": "Contributed Python code to the global data anonymization project \"gda-score.org\"",
        "exp-mpi-3": "Maintained a part-time schedule (20 hrs/week) while completing a Master's degree",

        "publications": "Publications & Content",
        "pub-devops-routine": "A cleaner and more reliable DevOps routine using build automation tools",
        "pub-az104": "How the AZ-104 Exam (Azure Administrator Certificate) Looks Like - My Exam Tips and Tricks",
        "pub-azure-prep": "How I prepare for Azure exams [Certified Azure Administrator] [AZ 104]",

        "technical-skills": "Technical Skills",
        "skills-cloud": "Cloud & Infrastructure",
        "skills-cicd": "CI/CD & DevOps",
        "skills-programming": "Programming & Scripting",
        "skills-security": "Security & Monitoring",
        "skills-systems": "Systems & Administration",

        "education": "Education",
        "msc-cs": "M.Sc. Computer Science",
        "beng-cs": "B.Eng. Computer Software Engineering",
        "university-rptu": "Rheinland-Pfälzische Technische Universität (RPTU)",
        "university-azad": "Azad University",
        "location-iran": "Tehran, Iran",

        "languages-soft-skills": "Languages & Soft Skills",
        "languages": "Languages",
        "soft-skills": "Soft Skills",
        "english-fluent": "English (Fluent)",
        "german-b1": "German (B1)",
        "persian-native": "Persian/Farsi (Native)",

        "contact-title": "Get In Touch",
        "contact-text-1": "Interested in working together? Have an exciting opportunity?",
        "contact-text-2": "Feel free to reach out - I'm always open to discussing new projects, creative ideas, or opportunities to be part of your vision.",
        "contact-email-label": "Send your offers or messages to:",
        "contact-response-time": "I typically respond to emails within 1 hour",

        "move-to-top": "Move to Top"
    },
    de: {
        // Header
        "name": "Mohammadali Forouzesh",
        "title": "DevOps Engineer | Kubernetes Administrator | Site Reliability Engineer",
        "pr-status": "Niederlassungserlaubnis für Deutschland",
        "download-cv": "Lebenslauf herunterladen",
        "pdf-version": "PDF Version",
        "yaml-version": "YAML Version",
        "contact-me": "Kontakt aufnehmen",
        "email-label": "E-Mail:",
        "phone-label": "Telefon:",
        "click-to-reveal": "zum Anzeigen >",
        "last-updated": "Zuletzt aktualisiert: November 2025",

        // Sections
        "about-me": "Über mich",
        "about-text": "🚀 Ergebnissorientierter DevOps Engineer mit einem Master in Informatik und 8+ Jahren Erfahrung in Cloud-Architektur ☁️, Azure, AWS, CI/CD und Kubernetes. 💪 Bewährte Fähigkeit, Produktionsreleases zu leiten und Infrastruktur zu automatisieren. 🛠️ Expertise in der Erstellung von End-to-End-Pipelines, Containerisierung 🐳 und proaktivem Monitoring 📊 für erfolgreiche Projektergebnisse.",

        "certifications": "Zertifizierungen",
        "cert-devops-azure": "Microsoft Certified DevOps Engineer Expert (AZ-400)",
        "cert-architect-azure": "Microsoft Certified Azure Solutions Architect Expert (AZ-305)",
        "cert-admin-azure": "Microsoft Certified Azure Administrator Associate (AZ-104)",
        "cert-fundamentals-azure": "Microsoft Certified Azure Fundamentals (AZ-900)",
        "cert-devsecops-hcl": "HCL Technologies Certified DevSecOps and SRE Associate",
        "cert-prompt-hcl": "HCL Technologies Certified Gen AI Prompt Engineering",
        "cert-genai-hcl": "HCL Technologies Certified AI & Gen AI Fundamentals",
        "cert-graphql-ndc": "NDC Konferenz Workshop GraphQL API - Porto 2022",

        "experience": "Berufserfahrung",
        "position-senior-devops": "Senior DevOps Engineer",
        "company-euroclear": "Euroclear",
        "location-brussels": "Brüssel, Belgien",
        "remote-germany": "(Remote aus Deutschland)",
        "duration-2023-present": "2023 - Heute",
        "exp-euroclear-1": "Entwurf und Verwaltung von 10+ CI/CD-Pipelines in Azure DevOps für verschiedene Anwendungsteams",
        "exp-euroclear-2": "Entwicklung und Wartung von 5+ Infrastructure-as-Code (IaC) Repositories mit Terraform",
        "exp-euroclear-3": "Erstellung von 20+ PowerShell-Skripten zur Automatisierung von Betriebsaufgaben und Bereitstellungen",
        "exp-euroclear-4": "Implementierung von automatisiertem Monitoring, Alerting und Log-Analyse für proaktives Systemmanagement",
        "exp-euroclear-5": "Leitung und Teilnahme an 15+ Produktionsrelease- und Launch-Zyklen",

        "position-lead-devops": "Projektleiter & Senior DevOps Consultant",
        "company-hcl": "HCL Technologies",
        "location-frankfurt": "Frankfurt, Deutschland",
        "exp-hcl-1": "Beratung als Senior DevOps Experte für Kunde Euroclear, Umsetzung wichtiger Projektlieferungen",
        "exp-hcl-2": "Bereitstellung von Infrastrukturautomatisierung, CI/CD und Monitoring-Lösungen",

        "position-senior-software": "Senior Software/DevOps Engineer",
        "company-matelso": "matelso GmbH",
        "location-kaiserslautern": "Kaiserslautern, Deutschland",
        "on-site": "(Vor Ort)",
        "duration-2021-2023": "2021 - 2023",
        "exp-matelso-1": "Architektur und Wartung von zentralen Backend GraphQL APIs für eine SaaS-Plattform",
        "exp-matelso-2": "Entwicklung und Verbesserung von 10+ Microservices mit .NET",
        "exp-matelso-3": "Entwurf und Wartung von 10+ CI/CD-Pipelines für automatisiertes Testen und Deployment",
        "exp-matelso-4": "Containerisierung und Bereitstellung von 10+ Services auf einem Kubernetes-Cluster",

        "position-research": "Software Engineer & Wissenschaftlicher Mitarbeiter",
        "company-mpi": "Max-Planck-Institut",
        "duration-2018-2020": "2018 - 2020",
        "exp-mpi-1": "Entwicklung interaktiver Datenvisualisierungs-Dashboards mit Python und Web-Technologien",
        "exp-mpi-2": "Beitrag von Python-Code zum globalen Datenanonymisierungsprojekt \"gda-score.org\"",
        "exp-mpi-3": "Teilzeitarbeit (20 Std./Woche) während des Masterstudiums",

        "publications": "Veröffentlichungen & Inhalte",
        // "pub-devops-routine": "Eine sauberere und zuverlässigere DevOps-Routine mit Build-Automatisierungstools",
        // "pub-az104": "Wie die AZ-104 Prüfung (Azure Administrator Zertifikat) aussieht - Meine Prüfungstipps und Tricks",
        // "pub-azure-prep": "Wie ich mich auf Azure-Prüfungen vorbereite [Certified Azure Administrator] [AZ 104]",

        "technical-skills": "Technische Fähigkeiten",
        "skills-cloud": "Cloud & Infrastruktur",
        "skills-cicd": "CI/CD & DevOps",
        "skills-programming": "Programmierung & Scripting",
        "skills-security": "Sicherheit & Monitoring",
        "skills-systems": "Systeme & Administration",

        "education": "Bildung",
        "msc-cs": "M.Sc. Informatik",
        "beng-cs": "B.Eng. Computer Software Engineering",
        "university-rptu": "Rheinland-Pfälzische Technische Universität (RPTU)",
        "university-azad": "Azad University",
        "location-iran": "Teheran, Iran",

        "languages-soft-skills": "Sprachen & Soft Skills",
        "languages": "Sprachen",
        "soft-skills": "Soft Skills",
        "english-fluent": "Englisch (Fließend)",
        "german-b1": "Deutsch (B1)",
        "persian-native": "Persisch/Farsi (Muttersprache)",

        "contact-title": "Kontakt aufnehmen",
        "contact-text-1": "Interesse an Zusammenarbeit? Haben Sie eine spannende Gelegenheit?",
        "contact-text-2": "Kontaktieren Sie mich gerne - ich bin immer offen für neue Projekte, kreative Ideen oder Möglichkeiten, Teil Ihrer Vision zu werden.",
        "contact-email-label": "Senden Sie Ihre Angebote oder Nachrichten an:",
        "contact-response-time": "Ich antworte in der Regel innerhalb von 1 Stunde auf E-Mails",

        "move-to-top": "Nach oben",
    }
};